"""Single source of truth for the app's fixed status/approval vocabularies.

Kept as plain strings/tuples (not a DB-level enum/CHECK constraint) to match
this project's existing pattern of validating these at the route layer.
"""

ROLE_ADMIN = "admin"
ROLE_COMPANY = "company"
ROLE_STUDENT = "student"

APPLICATION_STATUS_APPLIED = "applied"
APPLICATION_STATUS_SHORTLISTED = "shortlisted"
APPLICATION_STATUS_INTERVIEW = "interview"
APPLICATION_STATUS_OFFER = "offer"
APPLICATION_STATUS_REJECTED = "rejected"
APPLICATION_STATUS_PLACED = "placed"

APPLICATION_STATUSES = (
    APPLICATION_STATUS_APPLIED,
    APPLICATION_STATUS_SHORTLISTED,
    APPLICATION_STATUS_INTERVIEW,
    APPLICATION_STATUS_OFFER,
    APPLICATION_STATUS_REJECTED,
    APPLICATION_STATUS_PLACED,
)
# Statuses a Company may set via the decision endpoint (everything but the
# student-only entry state, "applied").
APPLICATION_DECISION_STATUSES = (
    APPLICATION_STATUS_SHORTLISTED,
    APPLICATION_STATUS_INTERVIEW,
    APPLICATION_STATUS_OFFER,
    APPLICATION_STATUS_REJECTED,
    APPLICATION_STATUS_PLACED,
)
TERMINAL_APPLICATION_STATUSES = (APPLICATION_STATUS_PLACED, APPLICATION_STATUS_REJECTED)

JOB_POSITION_STATUS_ONGOING = "ongoing"
JOB_POSITION_STATUS_COMPLETED = "completed"
JOB_POSITION_STATUSES = (JOB_POSITION_STATUS_ONGOING, JOB_POSITION_STATUS_COMPLETED)

COMPANY_APPROVAL_PENDING = "pending"
COMPANY_APPROVAL_APPROVED = "approved"
COMPANY_APPROVAL_REJECTED = "rejected"
COMPANY_APPROVAL_STATUSES = (
    COMPANY_APPROVAL_PENDING,
    COMPANY_APPROVAL_APPROVED,
    COMPANY_APPROVAL_REJECTED,
)
COMPANY_DECISION_STATUSES = (COMPANY_APPROVAL_APPROVED, COMPANY_APPROVAL_REJECTED)
