"""add photo/resume/logo/location fields

Revision ID: 0a87d6deb944
Revises: a820116b98ac
Create Date: 2026-08-01 21:09:43.533358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a87d6deb944'
down_revision = 'a820116b98ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_path', sa.String(length=255), nullable=True))

    with op.batch_alter_table('job_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=150), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('photo_path')

    with op.batch_alter_table('job_position', schema=None) as batch_op:
        batch_op.drop_column('location')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('logo_path')

    # ### end Alembic commands ###
