"""add job_position closed_by_admin flag

Revision ID: 1c34dde18af0
Revises: ce067e71ad3a
Create Date: 2026-08-09 16:01:16.767064

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1c34dde18af0"
down_revision = "ce067e71ad3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_position", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "closed_by_admin",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_position", schema=None) as batch_op:
        batch_op.drop_column("closed_by_admin")

    # ### end Alembic commands ###
