"""drive name, eligibility criteria, interview datetime

Revision ID: 3915587002cf
Revises: 0a87d6deb944
Create Date: 2026-08-02 19:28:13.900542

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3915587002cf"
down_revision = "0a87d6deb944"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("interview_datetime", sa.DateTime(), nullable=True)
        )

    with op.batch_alter_table("job_position", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("drive_name", sa.String(length=150), nullable=True)
        )
        batch_op.add_column(sa.Column("eligibility_criteria", sa.Text(), nullable=True))
        batch_op.drop_column("eligible_branches")
        batch_op.drop_column("min_cgpa")
        batch_op.drop_column("eligible_graduation_year")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_position", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("eligible_graduation_year", sa.INTEGER(), nullable=True)
        )
        batch_op.add_column(sa.Column("min_cgpa", sa.FLOAT(), nullable=True))
        batch_op.add_column(
            sa.Column("eligible_branches", sa.VARCHAR(length=255), nullable=True)
        )
        batch_op.drop_column("eligibility_criteria")
        batch_op.drop_column("drive_name")

    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.drop_column("interview_datetime")

    # ### end Alembic commands ###
