"""add user email, interview reminded at, email template, export job

Revision ID: 3dd33a7460af
Revises: e3ce95e7423a
Create Date: 2026-08-08 17:08:14.838993

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "3dd33a7460af"
down_revision = "e3ce95e7423a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_template",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=50), nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_table(
        "export_job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("job_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("file_path", sa.String(length=255), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("interview_reminded_at", sa.DateTime(), nullable=True)
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("email", sa.String(length=255), nullable=True))

    # Backfill a synthesized, unique placeholder for any pre-existing row before
    # the unique constraint goes on - username is already unique, so this can't collide.
    op.execute(
        "UPDATE users SET email = username || '@example.invalid' WHERE email IS NULL"
    )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_users_email", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint("uq_users_email", type_="unique")
        batch_op.drop_column("email")

    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.drop_column("interview_reminded_at")

    op.drop_table("export_job")
    op.drop_table("email_template")
    # ### end Alembic commands ###
