"""company overview and application feedback fields

Revision ID: 4818386d4da7
Revises: 3915587002cf
Create Date: 2026-08-07 22:42:37.023915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4818386d4da7'
down_revision = '3915587002cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interview_mode', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('company_remark', sa.Text(), nullable=True))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overview', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('overview')

    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('company_remark')
        batch_op.drop_column('interview_mode')

    # ### end Alembic commands ###
