"""add branch master table

Revision ID: 552c9791a2ad
Revises: 4818386d4da7
Create Date: 2026-08-07 23:35:35.471503

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "552c9791a2ad"
down_revision = "4818386d4da7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "branch",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    with op.batch_alter_table("student", schema=None) as batch_op:
        batch_op.add_column(sa.Column("branch_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_student_branch_id", "branch", ["branch_id"], ["id"]
        )
        batch_op.drop_column("branch")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("student", schema=None) as batch_op:
        batch_op.add_column(sa.Column("branch", sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint("fk_student_branch_id", type_="foreignkey")
        batch_op.drop_column("branch_id")

    op.drop_table("branch")
    # ### end Alembic commands ###
