"""add skill master table and student skills

Revision ID: 6e172a353b32
Revises: 552c9791a2ad
Create Date: 2026-08-07 23:44:44.273364

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6e172a353b32"
down_revision = "552c9791a2ad"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skill",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "student_skill",
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("skill_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skill.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student.id"],
        ),
        sa.PrimaryKeyConstraint("student_id", "skill_id"),
    )
    with op.batch_alter_table("student", schema=None) as batch_op:
        batch_op.drop_column("skills")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("student", schema=None) as batch_op:
        batch_op.add_column(sa.Column("skills", sa.TEXT(), nullable=True))

    op.drop_table("student_skill")
    op.drop_table("skill")
    # ### end Alembic commands ###
