"""add job_position_skill, drop job_position.skills_required

Revision ID: ce067e71ad3a
Revises: 3dd33a7460af
Create Date: 2026-08-08 23:25:27.319361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce067e71ad3a'
down_revision = '3dd33a7460af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_position_skill',
    sa.Column('job_position_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_position_id'], ['job_position.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('job_position_id', 'skill_id')
    )
    with op.batch_alter_table('job_position', schema=None) as batch_op:
        batch_op.drop_column('skills_required')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_position', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills_required', sa.TEXT(), nullable=True))

    op.drop_table('job_position_skill')
    # ### end Alembic commands ###
